import { promises as dns } from 'dns';
import type { SSHClient } from '../utils/ssh';
import { domainRepository } from '../repositories/domain.repository';
import { env } from '../config/env';
import { logger } from './logger';
import {
  writeProjectSites,
  reloadNginx,
  readCertificateNames,
  requestSSLCertificate,
  type ProjectSiteDomain,
} from '../workers/nginx-manager';

const CERT_EMAIL = 'ssl@pushify.app';

/**
 * example.com ↔ www.example.com. Returns null when stripping `www.` leaves no domain.
 * Whether the counterpart is actually served is decided by DNS, not by guessing what an apex
 * is: for app.example.com the counterpart www.app.example.com simply won't resolve.
 */
export function wwwCounterpart(domain: string): string | null {
  const d = domain.toLowerCase();
  if (d.startsWith('www.')) {
    const bare = d.slice(4);
    return bare.includes('.') ? bare : null;
  }
  return `www.${d}`;
}

async function resolvesTo(host: string, ip: string | null): Promise<boolean> {
  if (!ip) return false;
  try {
    return (await dns.resolve4(host)).includes(ip);
  } catch {
    return false;
  }
}

export interface SyncProjectSitesOptions {
  projectId: string;
  projectSlug: string;
  containerPort: number;
  /** The server's public IPv4: DNS is checked against it before Let's Encrypt is asked. */
  serverIp: string | null;
  /** Ask Let's Encrypt for missing certificates (deploy, verify) — settings edits don't. */
  requestCertificates?: boolean;
  /**
   * A shared runner: custom location blocks — raw config in the host's Nginx, able to read the
   * host's files or reach other customers' apps — are left out, whatever is stored.
   */
  sharedHost?: boolean;
  onProgress?: (message: string) => void;
}

export interface SyncedDomain {
  id: string;
  domain: string;
  kind: 'auto' | 'custom';
  ssl: boolean;
  /** the www / apex counterpart served as a redirect to this domain */
  aliases: string[];
  certificateError?: string;
}

interface PlannedDomain {
  id: string;
  domain: string;
  kind: 'auto' | 'custom';
  sslStatus: string | null;
  nginxSettings: ProjectSiteDomain['nginxSettings'];
  aliases: string[];
  pointsHere: boolean;
  certNames: string[] | null;
  certificateError?: string;
}

function toSite(p: PlannedDomain): ProjectSiteDomain {
  if (p.kind === 'auto') {
    return { domain: p.domain, kind: 'auto', ssl: true, nginxSettings: p.nginxSettings };
  }
  return {
    domain: p.domain,
    kind: 'custom',
    ssl: !!p.certNames,
    aliases: p.aliases,
    sslAliases: p.aliases.filter((a) => p.certNames?.includes(a)),
    nginxSettings: p.nginxSettings,
  };
}

/**
 * Bring a project's Nginx vhost in line with its domains in the database — all of them, in one
 * file — and (optionally) get the certificates that are missing.
 *
 * Every writer goes through here (deploy, verify, delete, settings), so adding
 * www.example.com can no longer wipe example.com, a deploy no longer drops every domain but
 * the primary, and custom Nginx settings survive deploys. A custom domain's www / apex
 * counterpart is served as a redirect to it (and put on its certificate) whenever its DNS points
 * at this server and it isn't a domain of its own.
 */
export async function syncProjectSites(
  ssh: SSHClient,
  options: SyncProjectSitesOptions
): Promise<{ success: boolean; message: string; domains: SyncedDomain[] }> {
  const progress = options.onProgress ?? (() => {});
  const rows = await domainRepository.findByProject(options.projectId);
  const ordered = [...rows].sort((a, b) => Number(b.isPrimary) - Number(a.isPrimary));

  // Auto subdomains live on the wildcard certificate, which only Pushify's shared host has.
  let wildcard = false;
  if (ordered.some((r) => r.isAutoGenerated) && env.PREVIEW_BASE_URL) {
    const dir = env.WILDCARD_SSL_PATH || `/etc/letsencrypt/live/${env.PREVIEW_BASE_URL}`;
    wildcard = (await ssh.exec(`test -f ${dir}/fullchain.pem && echo yes || echo no`)).stdout.trim() === 'yes';
  }

  const plan: PlannedDomain[] = [];
  for (const row of ordered) {
    const nginxSettings = { ...(row.nginxSettings ?? {}) };
    if (options.sharedHost && nginxSettings.customLocationBlocks) {
      delete nginxSettings.customLocationBlocks;
      progress(`⚠️ Custom location blocks on ${row.domain} ignored — they only run on your own server`);
      logger.warn({ domain: row.domain }, 'Custom location blocks skipped on a shared runner');
    }
    const base = {
      id: row.id,
      domain: row.domain,
      sslStatus: row.sslStatus ?? null,
      nginxSettings,
    };

    if (row.isAutoGenerated) {
      if (wildcard) plan.push({ ...base, kind: 'auto', aliases: [], pointsHere: true, certNames: null });
      continue;
    }

    const aliases: string[] = [];
    const counterpart = wwwCounterpart(row.domain);
    if (counterpart && !(await domainRepository.findByDomain(counterpart))) {
      if (await resolvesTo(counterpart, options.serverIp)) aliases.push(counterpart);
    }

    plan.push({
      ...base,
      kind: 'custom',
      aliases,
      pointsHere: await resolvesTo(row.domain, options.serverIp),
      certNames: await readCertificateNames(ssh, row.domain),
    });
  }

  const write = async () => {
    const result = await writeProjectSites(ssh, {
      projectSlug: options.projectSlug,
      containerPort: options.containerPort,
      domains: plan.map(toSite),
    });
    if (!result.success) return result;
    const reload = await reloadNginx(ssh);
    return reload.success ? result : { success: false, message: reload.message };
  };

  // 1. Serve what we can right now — new domains answer on port 80, which the challenge needs.
  const first = await write();
  if (!first.success) {
    return { success: false, message: first.message, domains: [] };
  }

  // 2. Certificates: only where the DNS already points here, and only what is missing.
  let changed = false;
  if (options.requestCertificates) {
    for (const p of plan) {
      if (p.kind !== 'custom') continue;
      const missingAliases = p.aliases.filter((a) => !p.certNames?.includes(a));
      if (p.certNames && missingAliases.length === 0) continue;

      if (!p.pointsHere) {
        if (!p.certNames) {
          progress(`⚠️ ${p.domain} does not point to this server yet (A record → ${options.serverIp ?? 'the server IP'}) — SSL skipped`);
        }
        continue;
      }

      const names = [p.domain, ...p.aliases].join(', ');
      progress(`🔐 Requesting SSL certificate for ${names}...`);
      let result = await requestSSLCertificate(ssh, p.domain, CERT_EMAIL, { aliases: p.aliases });
      if (!result.success && p.aliases.length && !p.certNames) {
        // Don't let a broken www record cost the main domain its certificate.
        progress(`⚠️ Certificate with ${p.aliases.join(', ')} failed — retrying for ${p.domain} alone`);
        result = await requestSSLCertificate(ssh, p.domain, CERT_EMAIL);
      }

      const before = p.certNames?.length ?? 0;
      p.certNames = await readCertificateNames(ssh, p.domain);
      if ((p.certNames?.length ?? 0) !== before) changed = true;

      if (result.success) {
        progress(`✅ SSL certificate ready for ${p.certNames?.join(', ') ?? p.domain}`);
      } else {
        p.certificateError = result.message;
        progress(`⚠️ SSL certificate failed for ${names}: ${result.message.slice(0, 300)}`);
        logger.warn({ domain: p.domain, error: result.message }, 'SSL certificate request failed');
      }
    }
  }

  // 3. Switch the new certificates on.
  if (changed) {
    const second = await write();
    if (!second.success) {
      return { success: false, message: second.message, domains: [] };
    }
  }

  // 4. Record what is actually being served.
  const synced: SyncedDomain[] = [];
  for (const p of plan) {
    const ssl = p.kind === 'auto' || !!p.certNames;
    const status = ssl ? 'active' : p.certificateError ? 'failed' : 'pending';
    if (status !== p.sslStatus) {
      try {
        await domainRepository.updateSslStatus(p.id, status);
      } catch (error) {
        logger.warn({ domainId: p.id, error: String(error) }, 'Could not record SSL status');
      }
    }
    synced.push({
      id: p.id,
      domain: p.domain,
      kind: p.kind,
      ssl,
      aliases: p.aliases,
      ...(p.certificateError ? { certificateError: p.certificateError } : {}),
    });
  }

  return { success: true, message: `Nginx configured for ${synced.length} domain(s)`, domains: synced };
}

/** One line for a deploy log: `example.com (+www.example.com) 🔒, app.pushify.dev 🔒`. */
export function describeSyncedDomains(domains: SyncedDomain[]): string {
  return domains
    .map((d) => `${d.domain}${d.aliases.length ? ` (+${d.aliases.join(', ')})` : ''}${d.ssl ? ' 🔒' : ''}`)
    .join(', ');
}
