import { describe, it, expect, beforeEach, vi } from 'vitest';

/**
 * A project's domains all live in one vhost file. The bug this guards: verifying
 * www.example.com rewrote that file with only www, so example.com lost its Nginx block and
 * certificate — and every deploy rewrote it with only the primary domain.
 */
const mocks = vi.hoisted(() => ({
  resolve4: vi.fn(),
  findByProject: vi.fn(),
  findByDomain: vi.fn(),
  updateSslStatus: vi.fn(),
}));

vi.mock('dns', () => ({ promises: { resolve4: mocks.resolve4 } }));
vi.mock('../config/env', () => ({
  env: { PREVIEW_BASE_URL: 'pushify.dev', WILDCARD_SSL_PATH: '/etc/letsencrypt/live/pushify.dev-0001' },
}));
vi.mock('../repositories/domain.repository', () => ({
  domainRepository: {
    findByProject: mocks.findByProject,
    findByDomain: mocks.findByDomain,
    updateSslStatus: mocks.updateSslStatus,
  },
}));

import { syncProjectSites, wwwCounterpart } from './project-sites';
import { generateProjectSitesConfig } from '../workers/nginx-manager';

const SERVER_IP = '203.0.113.10';

/** A server with nginx and certbot: certificates are a map of lineage → names. */
function fakeServer(options: { certs?: Record<string, string[]>; failNames?: string[]; wildcard?: boolean; nginxOk?: boolean } = {}) {
  const certs = new Map(Object.entries(options.certs ?? {}));
  const files = new Map<string, string>();
  const commands: string[] = [];
  const certbotCalls: string[][] = [];

  const ssh = {
    async exec(command: string) {
      commands.push(command);
      if (command.includes('openssl x509')) {
        const domain = command.match(/live\/([^/]+)\/fullchain\.pem/)![1];
        const names = certs.get(domain);
        return { code: 0, stdout: names ? names.map((n) => `DNS:${n}`).join('\n') : '__none__', stderr: '' };
      }
      if (command.includes('pushify.dev-0001/fullchain.pem')) {
        return { code: 0, stdout: options.wildcard ? 'yes' : 'no', stderr: '' };
      }
      if (command.startsWith('nginx -t')) {
        return { code: options.nginxOk === false ? 1 : 0, stdout: options.nginxOk === false ? 'emerg' : 'ok', stderr: '' };
      }
      if (command.includes('certbot certonly')) {
        const names = [...command.matchAll(/-d (\S+)/g)].map((m) => m[1]);
        const certName = command.match(/--cert-name (\S+)/)![1];
        certbotCalls.push(names);
        if (names.some((n) => options.failNames?.includes(n))) {
          return { code: 1, stdout: 'Challenge failed', stderr: '' };
        }
        certs.set(certName, names);
        return { code: 0, stdout: 'Successfully received certificate', stderr: '' };
      }
      if (command.startsWith('test -f /etc/nginx/sites-available/')) {
        return { code: 0, stdout: files.has(command.split(' ')[2]) ? 'yes' : '', stderr: '' };
      }
      return { code: 0, stdout: '', stderr: '' };
    },
    async uploadFile(content: string, path: string) {
      files.set(path, content);
    },
  };

  return {
    ssh: ssh as never,
    certbotCalls,
    commands,
    vhost: () => files.get('/etc/nginx/sites-available/pushify-yeli') ?? '',
  };
}

const row = (domain: string, extra: Record<string, unknown> = {}) => ({
  id: `id-${domain}`,
  domain,
  isPrimary: false,
  isAutoGenerated: false,
  sslStatus: 'pending',
  nginxSettings: {},
  ...extra,
});

/** DNS: these names have an A record pointing at the server. */
function dnsPointsHere(...names: string[]) {
  mocks.resolve4.mockImplementation(async (host: string) => {
    if (names.includes(host)) return [SERVER_IP];
    throw Object.assign(new Error('ENOTFOUND'), { code: 'ENOTFOUND' });
  });
}

const sync = (ssh: never, extra: Record<string, unknown> = {}) =>
  syncProjectSites(ssh, {
    projectId: 'project-1',
    projectSlug: 'yeli',
    containerPort: 3001,
    serverIp: SERVER_IP,
    requestCertificates: true,
    ...extra,
  });

beforeEach(() => {
  vi.clearAllMocks();
  mocks.findByDomain.mockImplementation(async (domain: string) =>
    (await mocks.findByProject()).find((r: { domain: string }) => r.domain === domain) ?? null
  );
});

describe('wwwCounterpart', () => {
  it('toggles www', () => {
    expect(wwwCounterpart('yeliapp.com')).toBe('www.yeliapp.com');
    expect(wwwCounterpart('www.yeliapp.com')).toBe('yeliapp.com');
    expect(wwwCounterpart('WWW.Yeliapp.com')).toBe('yeliapp.com');
  });

  it('never strips www down to a bare TLD', () => {
    expect(wwwCounterpart('www.com')).toBeNull();
  });
});

describe('syncProjectSites', () => {
  it('keeps yeliapp.com when www.yeliapp.com is added as its own domain — both served, both on SSL', async () => {
    mocks.findByProject.mockResolvedValue([
      row('yeliapp.com', { isPrimary: true }),
      row('www.yeliapp.com'),
    ]);
    dnsPointsHere('yeliapp.com', 'www.yeliapp.com');
    const server = fakeServer();

    const result = await sync(server.ssh);

    expect(result.success).toBe(true);
    expect(result.domains.map((d) => [d.domain, d.ssl, d.aliases])).toEqual([
      ['yeliapp.com', true, []],
      ['www.yeliapp.com', true, []],
    ]);
    const vhost = server.vhost();
    expect(vhost).toContain('ssl_certificate /etc/letsencrypt/live/yeliapp.com/fullchain.pem;');
    expect(vhost).toContain('ssl_certificate /etc/letsencrypt/live/www.yeliapp.com/fullchain.pem;');
    expect(mocks.updateSslStatus).toHaveBeenCalledWith('id-yeliapp.com', 'active');
    expect(mocks.updateSslStatus).toHaveBeenCalledWith('id-www.yeliapp.com', 'active');
  });

  it('serves www as a redirect to the apex and puts it on the same certificate', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true })]);
    dnsPointsHere('yeliapp.com', 'www.yeliapp.com');
    const server = fakeServer();

    const result = await sync(server.ssh);

    expect(server.certbotCalls).toEqual([['yeliapp.com', 'www.yeliapp.com']]);
    expect(server.commands.find((c) => c.includes('certbot'))).toContain('--cert-name yeliapp.com');
    expect(result.domains[0]).toMatchObject({ domain: 'yeliapp.com', ssl: true, aliases: ['www.yeliapp.com'] });

    const vhost = server.vhost();
    expect(vhost).toContain('server_name yeliapp.com www.yeliapp.com;');
    expect(vhost).toContain('return 301 https://yeliapp.com$request_uri;');
    // www over HTTPS redirects too, on the shared certificate
    expect(vhost).toMatch(/server_name www\.yeliapp\.com;[\s\S]*live\/yeliapp\.com\/fullchain\.pem[\s\S]*return 301 https:\/\/yeliapp\.com/);
  });

  it('works the other way round: the apex redirects to www when www is the domain added', async () => {
    mocks.findByProject.mockResolvedValue([row('www.yeliapp.com', { isPrimary: true })]);
    dnsPointsHere('yeliapp.com', 'www.yeliapp.com');
    const server = fakeServer();

    const result = await sync(server.ssh);

    expect(result.domains[0].aliases).toEqual(['yeliapp.com']);
    expect(server.vhost()).toContain('return 301 https://www.yeliapp.com$request_uri;');
  });

  it('leaves the counterpart out when its DNS does not point here', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true })]);
    dnsPointsHere('yeliapp.com');
    const server = fakeServer();

    const result = await sync(server.ssh);

    expect(server.certbotCalls).toEqual([['yeliapp.com']]);
    expect(result.domains[0].aliases).toEqual([]);
    expect(server.vhost()).not.toContain('www.yeliapp.com');
  });

  it('still gets the apex its certificate when the www challenge fails', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true })]);
    dnsPointsHere('yeliapp.com', 'www.yeliapp.com');
    const server = fakeServer({ failNames: ['www.yeliapp.com'] });

    const result = await sync(server.ssh);

    expect(result.domains[0].ssl).toBe(true);
    // www still redirects over plain HTTP; it is just not on the certificate
    expect(server.vhost()).toContain('server_name yeliapp.com www.yeliapp.com;');
    expect(server.vhost()).not.toMatch(/listen 443[^}]*server_name www\.yeliapp\.com;/);
  });

  it('adds www to an existing certificate instead of requesting a new lineage', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true, sslStatus: 'active' })]);
    dnsPointsHere('yeliapp.com', 'www.yeliapp.com');
    const server = fakeServer({ certs: { 'yeliapp.com': ['yeliapp.com'] } });

    await sync(server.ssh);

    const certbot = server.commands.find((c) => c.includes('certbot'))!;
    expect(certbot).toContain('--cert-name yeliapp.com');
    expect(certbot).toContain('--expand');
    expect(server.certbotCalls).toEqual([['yeliapp.com', 'www.yeliapp.com']]);
  });

  it('does not call certbot when the certificate already covers every name', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true, sslStatus: 'active' })]);
    dnsPointsHere('yeliapp.com', 'www.yeliapp.com');
    const server = fakeServer({ certs: { 'yeliapp.com': ['yeliapp.com', 'www.yeliapp.com'] } });

    await sync(server.ssh);

    expect(server.certbotCalls).toEqual([]);
    expect(mocks.updateSslStatus).not.toHaveBeenCalled();
  });

  it('skips SSL for a domain whose DNS is not pointed yet, and says so', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true })]);
    dnsPointsHere();
    const server = fakeServer();
    const progress: string[] = [];

    const result = await sync(server.ssh, { onProgress: (m: string) => progress.push(m) });

    expect(server.certbotCalls).toEqual([]);
    expect(result.domains[0].ssl).toBe(false);
    expect(progress.join('\n')).toContain('does not point to this server');
    // served over HTTP meanwhile, with the ACME challenge location in place
    expect(server.vhost()).toContain('proxy_pass http://127.0.0.1:3001;');
    expect(server.vhost()).toContain('/.well-known/acme-challenge/');
  });

  it('keeps the auto subdomain next to custom domains', async () => {
    mocks.findByProject.mockResolvedValue([
      row('yeli.pushify.dev', { isAutoGenerated: true, sslStatus: 'active' }),
      row('yeliapp.com', { isPrimary: true }),
    ]);
    dnsPointsHere('yeliapp.com');
    const server = fakeServer({ wildcard: true });

    const result = await sync(server.ssh);

    expect(result.domains.map((d) => d.domain)).toEqual(['yeliapp.com', 'yeli.pushify.dev']);
    expect(server.vhost()).toContain('ssl_certificate /etc/letsencrypt/live/pushify.dev-0001/fullchain.pem;');
    expect(server.vhost()).toContain('server_name yeli.pushify.dev;');
  });

  it('puts the previous file back when nginx rejects the new one', async () => {
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true })]);
    dnsPointsHere('yeliapp.com');
    const server = fakeServer({ nginxOk: false });

    const result = await sync(server.ssh);

    expect(result.success).toBe(false);
    expect(server.certbotCalls).toEqual([]);
    expect(server.commands.some((c) => c.includes('rm -f /etc/nginx/sites-enabled/pushify-yeli') || c.startsWith('cp -f'))).toBe(true);
  });
});

describe('syncProjectSites on a shared runner', () => {
  it('leaves custom location blocks out of the host config, whatever is stored', async () => {
    const blocks = 'location /leak { alias /etc/; autoindex on; }';
    mocks.findByProject.mockResolvedValue([row('yeliapp.com', { isPrimary: true, nginxSettings: { customLocationBlocks: blocks } })]);
    dnsPointsHere('yeliapp.com');

    const shared = fakeServer();
    await sync(shared.ssh, { sharedHost: true });
    expect(shared.vhost()).not.toContain('alias /etc/');

    const own = fakeServer();
    await sync(own.ssh);
    expect(own.vhost()).toContain(blocks);
  });
});

describe('generateProjectSitesConfig', () => {
  it('never writes a header that could break out of its quotes', () => {
    const config = generateProjectSitesConfig({
      projectSlug: 'yeli',
      containerPort: 3001,
      domains: [
        {
          domain: 'a.com',
          kind: 'custom',
          ssl: false,
          nginxSettings: {
            customHeaders: {
              'X-Ok': 'fine; value {with} $vars',
              'X-Evil': 'a"; } location /leak { alias /etc/; } #',
              'X-Newline': 'a\n    alias /etc/;',
              'Bad Name': 'x',
            },
          },
        },
      ],
    });

    expect(config).toContain('add_header X-Ok "fine; value {with} $vars";');
    expect(config).not.toContain('X-Evil');
    expect(config).not.toContain('X-Newline');
    expect(config).not.toContain('Bad Name');
    expect(config).not.toContain('alias /etc/');
  });

  it('gives each rate-limited domain its own zone, so two cannot collide', () => {
    const rateLimit = { enabled: true, requestsPerSecond: 10, burst: 20 };
    const config = generateProjectSitesConfig({
      projectSlug: 'yeli',
      containerPort: 3001,
      domains: [
        { domain: 'a.com', kind: 'custom', ssl: false, nginxSettings: { rateLimit } },
        { domain: 'b.com', kind: 'custom', ssl: false, nginxSettings: { rateLimit } },
      ],
    });

    expect(config).toContain('zone=pushify_yeli:10m');
    expect(config).toContain('zone=pushify_yeli_1:10m');
  });

  it('keeps per-domain Nginx settings (they used to be dropped on every deploy)', () => {
    const config = generateProjectSitesConfig({
      projectSlug: 'yeli',
      containerPort: 3001,
      domains: [{ domain: 'a.com', kind: 'custom', ssl: true, nginxSettings: { clientMaxBodySize: '512m', proxyPort: 8080 } }],
    });

    expect(config).toContain('client_max_body_size 512m;');
    expect(config).toContain('proxy_pass http://127.0.0.1:8080;');
  });
});
