import { promises as fs } from 'fs';
import path from 'path';
import { dockerAppWorkdir } from '../lib/normalize-root-directory';
import {
  DOCKERFILE_SYNTAX,
  NODE_BUILD_IMAGE,
  NODE_RUN_IMAGE,
  nodeInstallLines,
  nodeLightningcssGlibcFixLines,
  nodeRunnerUserLines,
  nextStandaloneRunnerLines,
} from '../lib/platform-docker';
import { detectNodeFrameworkFromPackageJson } from './nodejs-detect';
import type { Buildpack, BuildpackDetectResult, BuildpackConfig } from './types';

/** `CMD ["sh", "-c", …]` so a start command may use env vars, `&&` and pipes. */
const shCmd = (cmd: string): string => `CMD ["sh", "-c", ${JSON.stringify(cmd)}]`;

export const nodejsBuildpack: Buildpack = {
  id: 'nodejs',
  name: 'Node.js',
  frameworks: ['nextjs', 'nuxt', 'react', 'vue', 'svelte', 'astro', 'remix', 'express', 'fastify', 'hono', 'koa', 'nodejs'],

  async detect(workDir: string, rootDir: string): Promise<BuildpackDetectResult> {
    try {
      const pkgPath = path.join(workDir, rootDir === '.' ? '' : rootDir, 'package.json');
      const content = await fs.readFile(pkgPath, 'utf-8');
      const pkg = JSON.parse(content);
      return detectNodeFrameworkFromPackageJson(pkg);
    } catch {
      return { detected: false, framework: '', confidence: 0 };
    }
  },

  generateDockerfile(config: BuildpackConfig): string {
    const cfg = config as BuildpackConfig & { framework?: string; nextStandalone?: boolean };
    const framework = cfg.framework || 'nodejs';
    const nextStandalone = cfg.nextStandalone === true;
    const port = config.port || this.getDefaultPort(framework);
    const install = config.installCommand || this.getDefaultInstallCommand(framework);
    const workdir = dockerAppWorkdir();

    const envEntries = config.envVars ? Object.entries(config.envVars) : [];
    const argLines = envEntries.map(([k]) => `ARG ${k}`).join('\n');
    const envLines = envEntries.map(([k]) => `ENV ${k}=$${k}`).join('\n');

    // build / start from the dashboard or pushify.yaml win over the framework defaults
    // (they used to be ignored by everything but the generic path).
    const build = config.buildCommand || 'npm run build';
    const start = config.startCommand || null;
    if (framework === 'nextjs') return this._nextjs(workdir, install, build, start, port, argLines, envLines, nextStandalone);
    if (framework === 'nuxt') return this._nuxt(workdir, install, build, start, port, argLines, envLines);
    if (['react', 'vue', 'svelte', 'astro'].includes(framework)) {
      // SvelteKit's static adapter writes build/, the others dist/.
      const defaultOut = framework === 'svelte' ? 'build' : 'dist';
      return this._static(workdir, install, build, config.outputDirectory || defaultOut, port);
    }
    return this._generic(
      workdir,
      install,
      config.buildCommand,
      config.startCommand || this.getDefaultStartCommand(framework),
      port
    );
  },

  getDefaultPort(framework?: string): number {
    if (framework === 'nextjs' || framework === 'nuxt' || framework === 'remix') return 3000;
    return 3000;
  },

  getDefaultBuildCommand(): string {
    return 'npm run build';
  },

  getDefaultStartCommand(framework?: string): string {
    if (framework === 'nuxt') return 'node .output/server/index.mjs';
    return 'npm start';
  },

  getDefaultInstallCommand(): string {
    return 'npm install --legacy-peer-deps';
  },

  getHealthCheckPath(): string {
    return '/';
  },

  _nodeBuilderHeader(): string {
    return `${DOCKERFILE_SYNTAX}# Generated by Pushify — glibc Linux (Debian slim)\nFROM ${NODE_BUILD_IMAGE} AS builder\nWORKDIR /app\nCOPY package*.json ./\n`;
  },

  _nextjs(
    workdir: string,
    install: string,
    build: string,
    start: string | null,
    port: number,
    argLines: string,
    envLines: string,
    standalone: boolean
  ): string {
    // A custom start command applies to the full runner; standalone output ships its own
    // server.js entrypoint.
    const cmd = start ? shCmd(start) : 'CMD ["npm", "start"]';
    const runner = standalone
      ? nextStandaloneRunnerLines(workdir, port)
      : `
FROM ${NODE_RUN_IMAGE} AS runner
WORKDIR ${workdir}
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
${nodeRunnerUserLines()}
COPY --from=builder ${workdir}/public ./public
COPY --from=builder ${workdir}/.next ./.next
COPY --from=builder ${workdir}/node_modules ./node_modules
COPY --from=builder ${workdir}/package.json ./package.json
USER nextjs
EXPOSE ${port}
ENV PORT=${port}
ENV HOSTNAME="0.0.0.0"
${cmd}
`;

    const standaloneNote = standalone
      ? '# Next.js standalone output (next.config output: "standalone")\n'
      : '';

    return `${this._nodeBuilderHeader()}${standaloneNote}${nodeInstallLines(install)}
${nodeLightningcssGlibcFixLines()}
${argLines}
${envLines}
ENV NEXT_TELEMETRY_DISABLED=1
RUN --mount=type=cache,target=${workdir}/.next/cache ${build}
${runner}`;
  },

  _nuxt(workdir: string, install: string, build: string, start: string | null, port: number, argLines: string, envLines: string): string {
    const cmd = start ? shCmd(start) : 'CMD ["node", ".output/server/index.mjs"]';
    return `${this._nodeBuilderHeader()}${nodeInstallLines(install)}
${nodeLightningcssGlibcFixLines()}
${argLines}
${envLines}
RUN --mount=type=cache,target=${workdir}/.nuxt ${build}

FROM ${NODE_RUN_IMAGE} AS runner
WORKDIR ${workdir}
ENV NODE_ENV=production
COPY --from=builder ${workdir}/.output ./.output
EXPOSE ${port}
ENV PORT=${port}
ENV HOST="0.0.0.0"
${cmd}
`;
  },

  _static(workdir: string, install: string, buildCmd: string, outDir: string, port: number): string {
    // The deploy workers map the host port to the project's configured port —
    // nginx must listen on that same port, not a hardcoded 80. $uri must reach
    // the config unescaped: shell single quotes already preserve it literally.
    // A repo-root nginx.conf overrides the generated server config (it must
    // listen on the same port); it's staged in the builder because the runner
    // only receives the build output directory.
    return `${this._nodeBuilderHeader()}${nodeInstallLines(install)}
${nodeLightningcssGlibcFixLines()}
RUN ${buildCmd}
RUN mkdir -p /pushify-nginx && if [ -f nginx.conf ]; then cp nginx.conf /pushify-nginx/default.conf; sed -E -i 's/(listen[[:space:]]+)([^ ;]*:)?[0-9]+/\\1\\2${port}/g; s/(listen[[:space:]][^;]*) ssl/\\1/g; s/(listen[[:space:]][^;]*) http2/\\1/g; s#root[[:space:]]+[^;]+#root /usr/share/nginx/html#g' /pushify-nginx/default.conf; echo 'Pushify: nginx.conf normalized to listen on ${port} and serve from /usr/share/nginx/html'; else echo 'server { listen ${port}; root /usr/share/nginx/html; location ~* \\.(?:css|js|mjs|json|png|jpg|jpeg|gif|svg|webp|avif|ico|woff2?|ttf|eot|map)$ { expires 1y; add_header Cache-Control "public, immutable"; try_files $uri =404; } location / { try_files $uri $uri.html $uri/ /index.html; add_header Cache-Control "no-cache"; } }' > /pushify-nginx/default.conf; fi

FROM nginx:alpine AS runner
COPY --from=builder ${workdir}/${outDir} /usr/share/nginx/html
COPY --from=builder /pushify-nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE ${port}
CMD ["nginx", "-g", "daemon off;"]
`;
  },

  _generic(
    workdir: string,
    install: string,
    buildCmd: string | null | undefined,
    startCmd: string,
    port: number
  ): string {
    // No build command set: run the package's own "build" script when it has one (tsc, bundlers)
    // — like Heroku / Railway. Without it a TypeScript API started from dist/ that was never built.
    const buildStep = `RUN ${buildCmd || 'npm run build --if-present'}\n`;
    return `${this._nodeBuilderHeader()}${nodeInstallLines(install)}
${nodeLightningcssGlibcFixLines()}
${buildStep}EXPOSE ${port}
ENV PORT=${port}
ENV NODE_ENV=production
CMD ${JSON.stringify(startCmd.split(' '))}
`;
  },
} as Buildpack & Record<string, any>;
