import { describe, it, expect, vi, beforeAll, afterAll, beforeEach } from 'vitest';

/** Acceptable Use queue and enforcement against a real Postgres (ACCOUNT_DELETION_TEST_DATABASE_URL). */
const TEST_URL = process.env.ACCOUNT_DELETION_TEST_DATABASE_URL;

vi.mock('../db', async () => {
  const pg = (await import('pg')).default;
  const { drizzle } = await import('drizzle-orm/node-postgres');
  const schema = await import('../db/schema');
  const pool = new pg.Pool({ connectionString: process.env.ACCOUNT_DELETION_TEST_DATABASE_URL || 'postgresql:///nonexistent', max: 4 });
  return { db: drizzle(pool, { schema }), __pool: pool };
});

const mocks = vi.hoisted(() => ({
  pause: vi.fn(async () => true),
  resume: vi.fn(async () => true),
  suspendedEmail: vi.fn(async () => undefined),
  reinstatedEmail: vi.fn(async () => undefined),
  adminNotify: vi.fn(),
}));

vi.mock('../lib/project-remote-cleanup', () => ({
  pauseProjectContainers: mocks.pause,
  resumeProjectContainers: mocks.resume,
}));
vi.mock('../lib/email', () => ({
  sendProjectSuspendedEmail: mocks.suspendedEmail,
  sendProjectReinstatedEmail: mocks.reinstatedEmail,
}));
vi.mock('./admin-notify.service', () => ({ adminNotify: mocks.adminNotify }));
vi.mock('../config/env', async (importOriginal) => {
  const actual = (await importOriginal()) as { env: Record<string, unknown> };
  return {
    env: {
      ...actual.env,
      PREVIEW_BASE_URL: 'pushify.dev',
      ABUSE_DETECTION_ENABLED: true,
      ABUSE_CONTACT_EMAIL: 'abuse@pushify.dev',
      FRONTEND_URL: 'https://pushify.dev',
    },
  };
});

import { and, eq, sql } from 'drizzle-orm';
import { db } from '../db';
import {
  abuseActions,
  abuseFlags,
  activityLogs,
  containerMetrics,
  domains,
  organizationMembers,
  organizations,
  projects,
  servers,
  users,
} from '../db/schema';
import { loadAbuseRules } from '../lib/abuse/rules';
import { scanForAbuse } from '../lib/abuse/scan';
import { abuseService, projectIsCovered } from './abuse.service';
import { projectService } from './project.service';
import { enforceSuspensions, sweepRuntimeSignals } from '../workers/abuse-runtime.worker';

const PREFIX = 'abuse-test-';
const ctx = {} as { orgId: string; userId: string; adminId: string; runnerProject: string; byosOwnDomain: string; byosSubdomain: string; managedProject: string };

async function project(name: string, serverId: string | null) {
  const [p] = await db.insert(projects).values({ organizationId: ctx.orgId, name, slug: `${PREFIX}${name}-${Date.now()}`, serverId }).returning();
  return p.id;
}

describe.skipIf(!TEST_URL)('Acceptable Use enforcement (real Postgres)', () => {
  beforeAll(async () => {
    await db.execute(sql`delete from organizations where name like ${PREFIX + '%'}`);
    await db.execute(sql`delete from users where email like ${PREFIX + '%'}`);
    const stamp = Date.now();
    const [o] = await db.insert(organizations).values({ name: `${PREFIX}${stamp}`, slug: `${PREFIX}${stamp}` }).returning();
    const [u] = await db.insert(users).values({ email: `${PREFIX}${stamp}@example.com`, name: 'owner' }).returning();
    const [a] = await db.insert(users).values({ email: `${PREFIX}admin-${stamp}@example.com`, name: 'admin' }).returning();
    await db.insert(organizationMembers).values({ organizationId: o.id, userId: u.id, role: 'owner' });
    Object.assign(ctx, { orgId: o.id, userId: u.id, adminId: a.id });

    const [managed] = await db
      .insert(servers)
      .values({ organizationId: o.id, name: 'm', provider: 'hetzner', region: 'fsn1', isManaged: true })
      .returning();
    const [byos] = await db
      .insert(servers)
      .values({ organizationId: o.id, name: 'b', provider: 'self_hosted', region: 'own', isManaged: false })
      .returning();

    ctx.runnerProject = await project('runner', null);
    ctx.managedProject = await project('managed', managed.id);
    ctx.byosOwnDomain = await project('byos-own', byos.id);
    ctx.byosSubdomain = await project('byos-sub', byos.id);
    await db.insert(domains).values([
      { projectId: ctx.byosOwnDomain, domain: `${PREFIX}${stamp}.example.org` },
      { projectId: ctx.byosSubdomain, domain: `${PREFIX}${stamp}.pushify.dev`, isAutoGenerated: true },
      { projectId: ctx.runnerProject, domain: `${PREFIX}runner-${stamp}.pushify.dev`, isAutoGenerated: true },
    ]);
  });

  afterAll(async () => {
    await db.execute(sql`delete from organizations where name like ${PREFIX + '%'}`);
    await db.execute(sql`delete from users where email like ${PREFIX + '%'}`);
    await db.execute(sql`delete from abuse_flags where reporter_email like ${PREFIX + '%'}`);
    const { __pool } = (await import('../db')) as unknown as { __pool: { end(): Promise<void> } };
    await __pool.end();
  });

  beforeEach(() => {
    for (const m of Object.values(mocks)) m.mockClear();
  });

  it('applies the hosted-service rules to runners, managed servers and the platform subdomain only', async () => {
    expect(await projectIsCovered(ctx.runnerProject)).toBe(true);
    expect(await projectIsCovered(ctx.managedProject)).toBe(true);
    expect(await projectIsCovered(ctx.byosSubdomain)).toBe(true);
    expect(await projectIsCovered(ctx.byosOwnDomain)).toBe(false);
  });

  it('writes nothing below the threshold, then opens one flag per source and merges later findings', async () => {
    const rules = loadAbuseRules();
    const weak = scanForAbuse({ files: [{ path: 'a.js', content: 'new WebSocket(u)' }] }, rules);
    expect(await abuseService.recordFinding({ projectId: ctx.managedProject, organizationId: ctx.orgId, source: 'deploy_scan', result: weak })).toBeNull();

    const first = scanForAbuse({ files: [{ path: 'Dockerfile', content: 'RUN git clone https://github.com/TelegramMessenger/MTProxy' }] }, rules);
    const a = await abuseService.recordFinding({ projectId: ctx.managedProject, organizationId: ctx.orgId, source: 'deploy_scan', result: first });
    expect(a?.created).toBe(true);
    expect(mocks.adminNotify).toHaveBeenCalledWith('abuse.flagged', expect.objectContaining({ source: 'deploy_scan' }));

    const second = scanForAbuse({ image: 'teddysun/xray:latest' }, rules);
    const b = await abuseService.recordFinding({ projectId: ctx.managedProject, organizationId: ctx.orgId, source: 'deploy_scan', result: second });
    expect(b).toEqual({ flagId: a!.flagId, created: false });
    expect(mocks.adminNotify).toHaveBeenCalledTimes(1);

    const open = await db.select().from(abuseFlags).where(and(eq(abuseFlags.projectId, ctx.managedProject), eq(abuseFlags.status, 'open')));
    expect(open).toHaveLength(1);
    expect(open[0].reasons.map((r) => r.ruleId).sort()).toEqual(['mtproxy', 'proxy-image']);
    expect(open[0].score).toBe(120);
  });

  it('suspends: stops the app, blocks resuming, emails the owner and writes the audit trail', async () => {
    const [flag] = await db.select().from(abuseFlags).where(eq(abuseFlags.projectId, ctx.managedProject));
    const res = await abuseService.suspendProject({
      projectId: ctx.managedProject,
      adminUserId: ctx.adminId,
      reason: 'Runs a VLESS relay and an MTProxy on a managed server',
      clause: 'proxy-vpn',
      endsAt: null,
      flagId: flag.id,
    });
    expect(res).toEqual({ containersStopped: true, ownerNotified: true });
    expect(mocks.pause).toHaveBeenCalledTimes(1);

    const [p] = await db.select().from(projects).where(eq(projects.id, ctx.managedProject));
    expect(p.status).toBe('paused');
    expect(p.suspendedAt).toBeInstanceOf(Date);
    expect(p.suspensionClause).toBe('proxy-vpn');

    expect(mocks.suspendedEmail).toHaveBeenCalledWith(
      expect.stringContaining(PREFIX),
      expect.objectContaining({ clause: expect.stringContaining('§2.1'), appealEmail: 'abuse@pushify.dev', endsAt: null }),
    );
    const actions = await db.select().from(abuseActions).where(eq(abuseActions.projectId, ctx.managedProject));
    expect(actions.map((x) => x.action)).toEqual(['suspend']);
    expect(actions[0]).toMatchObject({ adminUserId: ctx.adminId, flagId: flag.id });
    const logged = await db.select().from(activityLogs).where(and(eq(activityLogs.projectId, ctx.managedProject), eq(activityLogs.action, 'project.suspended')));
    expect(logged).toHaveLength(1);
    const [after] = await db.select().from(abuseFlags).where(eq(abuseFlags.id, flag.id));
    expect(after.status).toBe('actioned');

    // The owner cannot undo it by resuming
    await expect(projectService.updateStatus(ctx.managedProject, ctx.orgId, ctx.userId, 'active', 'en')).rejects.toMatchObject({ status: 403 });
    await expect(
      abuseService.suspendProject({ projectId: ctx.managedProject, adminUserId: ctx.adminId, reason: 'again and again', clause: 'other', endsAt: null }),
    ).rejects.toMatchObject({ status: 409 });
  });

  it('keeps a suspension enforced: stops the suspended project again, and says when it cannot', async () => {
    const first = await enforceSuspensions();
    expect(first.checked).toBeGreaterThanOrEqual(1);
    expect(mocks.pause).toHaveBeenCalledWith(expect.objectContaining({ id: ctx.managedProject }));
    expect(first.notStopped).toBe(0);

    mocks.pause.mockResolvedValueOnce(false);
    const second = await enforceSuspensions();
    expect(second.notStopped).toBeGreaterThanOrEqual(1);
  });

  it('unsuspends: starts the app again, notifies the owner and logs it', async () => {
    const res = await abuseService.unsuspendProject({ projectId: ctx.managedProject, adminUserId: ctx.adminId, note: 'Appeal accepted' });
    expect(res).toEqual({ containersStarted: true, ownerNotified: true });
    expect(mocks.resume).toHaveBeenCalledTimes(1);
    const [p] = await db.select().from(projects).where(eq(projects.id, ctx.managedProject));
    expect(p).toMatchObject({ status: 'active', suspendedAt: null, suspensionReason: null });
    const actions = await db.select().from(abuseActions).where(eq(abuseActions.projectId, ctx.managedProject));
    expect(actions.map((x) => x.action).sort()).toEqual(['suspend', 'unsuspend']);
    expect(mocks.reinstatedEmail).toHaveBeenCalledTimes(1);
  });

  it('files outside reports into the same queue, matched to a project by host when possible', async () => {
    const [d] = await db.select().from(domains).where(eq(domains.projectId, ctx.byosSubdomain));
    await abuseService.submitReport({ url: `https://${d.domain}/ws/123`, email: `${PREFIX}reporter@example.com`, category: 'proxy-vpn', details: 'This site runs a VPN relay.' });
    await abuseService.submitReport({ url: 'https://unknown.example.net/', email: `${PREFIX}reporter@example.com`, category: 'phishing', details: 'Phishing page here.' });
    const reports = await db.select().from(abuseFlags).where(eq(abuseFlags.source, 'report'));
    const mine = reports.filter((r) => r.reporterEmail?.startsWith(PREFIX));
    expect(mine.find((r) => r.reportedUrl?.includes(d.domain))?.projectId).toBe(ctx.byosSubdomain);
    expect(mine.find((r) => r.reportedUrl?.includes('unknown'))?.projectId).toBeNull();
    expect(mocks.adminNotify).toHaveBeenCalledWith('abuse.reported', expect.anything());
  });

  it('runtime sweep flags a relay pattern (in ≈ out at high volume) and leaves a quiet app alone', async () => {
    const GIB = 1024 ** 3;
    const now = Date.now();
    const row = (projectId: string, minutesAgo: number, rx: number, tx: number) => ({
      projectId,
      containerName: 'c',
      cpuPercent: 1,
      memoryUsageBytes: 1,
      memoryLimitBytes: 1,
      memoryPercent: 1,
      networkRxBytes: rx,
      networkTxBytes: tx,
      blockReadBytes: 0,
      blockWriteBytes: 0,
      containerStatus: 'running',
      pids: 1,
      recordedAt: new Date(now - minutesAgo * 60_000),
    });
    await db.insert(containerMetrics).values([
      row(ctx.runnerProject, 600, 0, 0),
      row(ctx.runnerProject, 300, 30 * GIB, 31 * GIB),
      row(ctx.runnerProject, 5, 58 * GIB, 60 * GIB),
      row(ctx.byosSubdomain, 600, 0, 0),
      row(ctx.byosSubdomain, 5, 1 * GIB, 2 * GIB),
    ]);

    await sweepRuntimeSignals();
    const runtime = await db.select().from(abuseFlags).where(eq(abuseFlags.source, 'runtime'));
    const runner = runtime.find((f) => f.projectId === ctx.runnerProject);
    expect(runner?.reasons.map((r) => r.ruleId).sort()).toEqual(['runtime-egress', 'runtime-relay']);
    expect(runtime.find((f) => f.projectId === ctx.byosSubdomain)).toBeUndefined();
  });
});
