import { HTTPException } from 'hono/http-exception';
import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import { db } from '../db';
import { projects, domains } from '../db/schema/projects';
import { servers } from '../db/schema/servers';
import { organizations } from '../db/schema/organizations';
import { users } from '../db/schema/users';
import { abuseFlags, abuseActions, type AbuseReason } from '../db/schema/abuse';
import { env } from '../config/env';
import { logger } from '../lib/logger';
import { loadAbuseRules } from '../lib/abuse/rules';
import { scoreReasons, type ScanResult } from '../lib/abuse/scan';
import { activityService } from './activity.service';
import { adminNotify } from './admin-notify.service';
import { organizationRepository } from '../repositories/organization.repository';
import { sendProjectSuspendedEmail, sendProjectReinstatedEmail } from '../lib/email';

/**
 * Acceptable Use enforcement for the hosted service. Detection only ever *queues* a project for
 * a person to look at; suspension is an admin action (or, with ABUSE_AUTO_SUSPEND, a narrow
 * automatic one). Everything is off unless ABUSE_DETECTION_ENABLED is set, so self-hosted
 * installs carry none of it.
 */

export type AbuseSource = 'deploy_scan' | 'runtime' | 'report';

/** Policy sections an admin can cite; the frontend Acceptable Use page uses the same anchors. */
export const AUP_CLAUSES = {
  'proxy-vpn': 'Acceptable Use §2.1 — proxy, VPN, tunnel and relay services',
  scanning: 'Acceptable Use §2.2 — network and port scanning',
  'spam-malware': 'Acceptable Use §1 — spam and malware',
  'attacks-mining': 'Acceptable Use §1 — attacks, DDoS and cryptocurrency mining',
  'unauthorized-access': 'Acceptable Use §1 — unauthorized access',
  illegal: 'Acceptable Use §1 — illegal content',
  other: 'Acceptable Use',
} as const;
export type AupClause = keyof typeof AUP_CLAUSES;

export function abuseDetectionEnabled(): boolean {
  return env.ABUSE_DETECTION_ENABLED === true;
}

function platformDomainSuffix(): string | null {
  const base = env.PREVIEW_BASE_URL?.trim().replace(/^\.+/, '').toLowerCase();
  return base ? `.${base}` : null;
}

/**
 * Whether the hosted-service rules apply to a project: it runs on a managed server or a shared
 * runner (no server of its own), or it is reachable on the platform subdomain. A project on the
 * customer's own server with only the customer's own domains is not covered.
 */
export function isCoveredByPolicy(input: {
  serverId: string | null;
  server: { isManaged: boolean; provider: string } | null;
  domains: { domain: string; isAutoGenerated: boolean }[];
}): boolean {
  if (!input.serverId) return true;
  if (input.server && input.server.isManaged && input.server.provider !== 'self_hosted') return true;
  const suffix = platformDomainSuffix();
  return input.domains.some((d) => d.isAutoGenerated || (suffix !== null && d.domain.toLowerCase().endsWith(suffix)));
}

export async function projectIsCovered(projectId: string): Promise<boolean> {
  const [project] = await db
    .select({ serverId: projects.serverId })
    .from(projects)
    .where(eq(projects.id, projectId))
    .limit(1);
  if (!project) return false;
  const server = project.serverId
    ? (
        await db
          .select({ isManaged: servers.isManaged, provider: servers.provider })
          .from(servers)
          .where(eq(servers.id, project.serverId))
          .limit(1)
      )[0] ?? null
    : null;
  const projectDomains = await db
    .select({ domain: domains.domain, isAutoGenerated: domains.isAutoGenerated })
    .from(domains)
    .where(eq(domains.projectId, projectId));
  return isCoveredByPolicy({ serverId: project.serverId, server, domains: projectDomains });
}

function mergeReasons(a: AbuseReason[], b: AbuseReason[]): AbuseReason[] {
  const byRule = new Map<string, AbuseReason>();
  for (const r of [...a, ...b]) if (!byRule.has(r.ruleId)) byRule.set(r.ruleId, r);
  return [...byRule.values()];
}

async function ownerContact(organizationId: string): Promise<string | null> {
  const owner = await organizationRepository.findOwner(organizationId);
  if (!owner) return null;
  const [user] = await db.select({ email: users.email }).from(users).where(eq(users.id, owner.userId)).limit(1);
  return user?.email ?? null;
}

export const abuseService = {
  /**
   * Record a scan or runtime finding. Below the flag threshold nothing is written. At or above
   * it, the project's open flag for that source is created or updated (reasons merged, score
   * recomputed) and the operators are told once, when the flag is first opened.
   */
  async recordFinding(input: {
    projectId: string;
    organizationId: string;
    deploymentId?: string | null;
    source: Exclude<AbuseSource, 'report'>;
    result: ScanResult;
  }): Promise<{ flagId: string; created: boolean } | null> {
    if (!input.result.flagged) return null;
    const rules = loadAbuseRules();

    const [open] = await db
      .select()
      .from(abuseFlags)
      .where(and(eq(abuseFlags.projectId, input.projectId), eq(abuseFlags.source, input.source), eq(abuseFlags.status, 'open')))
      .limit(1);

    if (open) {
      const merged = scoreReasons(mergeReasons(open.reasons, input.result.reasons), rules);
      await db
        .update(abuseFlags)
        .set({
          reasons: merged.reasons,
          score: merged.score,
          deploymentId: input.deploymentId ?? open.deploymentId,
          updatedAt: new Date(),
        })
        .where(eq(abuseFlags.id, open.id));
      return { flagId: open.id, created: false };
    }

    const [flag] = await db
      .insert(abuseFlags)
      .values({
        projectId: input.projectId,
        organizationId: input.organizationId,
        deploymentId: input.deploymentId ?? null,
        source: input.source,
        score: input.result.score,
        reasons: input.result.reasons,
      })
      .returning({ id: abuseFlags.id });

    const [project] = await db
      .select({ slug: projects.slug, name: projects.name })
      .from(projects)
      .where(eq(projects.id, input.projectId))
      .limit(1);
    adminNotify('abuse.flagged', {
      project: project?.slug ?? input.projectId,
      source: input.source,
      score: input.result.score,
      reasons: input.result.reasons.map((r) => r.ruleId).join(', '),
      review: `${env.FRONTEND_URL}/admin/abuse`,
    });
    logger.warn({ projectId: input.projectId, source: input.source, score: input.result.score }, 'Project flagged for Acceptable Use review');
    return { flagId: flag.id, created: true };
  },

  /**
   * An outside report from the /abuse form. The reported URL's host is matched to a project by
   * its domains; an unmatched report still lands in the queue so nothing is dropped.
   */
  async submitReport(input: { url: string; email: string; category: string; details: string }): Promise<{ id: string }> {
    let host = '';
    try {
      host = new URL(input.url).hostname.toLowerCase();
    } catch {
      throw new HTTPException(400, { message: 'Enter the full URL, starting with https://' });
    }
    const [match] = host
      ? await db
          .select({ projectId: domains.projectId, organizationId: projects.organizationId })
          .from(domains)
          .innerJoin(projects, eq(projects.id, domains.projectId))
          .where(eq(domains.domain, host))
          .limit(1)
      : [];

    const [flag] = await db
      .insert(abuseFlags)
      .values({
        projectId: match?.projectId ?? null,
        organizationId: match?.organizationId ?? null,
        source: 'report',
        score: 0,
        reasons: [{ ruleId: `report-${input.category}`, weight: 0, strength: 'weak', message: `Reported as ${input.category}` }],
        reportedUrl: input.url.slice(0, 500),
        reporterEmail: input.email.slice(0, 255),
        reportText: input.details.slice(0, 5000),
      })
      .returning({ id: abuseFlags.id });

    adminNotify('abuse.reported', {
      url: input.url,
      category: input.category,
      matchedProject: match?.projectId ?? 'none',
      review: `${env.FRONTEND_URL}/admin/abuse`,
    });
    return { id: flag.id };
  },

  async listFlags(params: { status: 'open' | 'dismissed' | 'actioned' | 'all'; limit: number; offset: number }) {
    const where = params.status === 'all' ? undefined : eq(abuseFlags.status, params.status);
    const rows = await db
      .select({
        id: abuseFlags.id,
        source: abuseFlags.source,
        status: abuseFlags.status,
        score: abuseFlags.score,
        reasons: abuseFlags.reasons,
        reportedUrl: abuseFlags.reportedUrl,
        reporterEmail: abuseFlags.reporterEmail,
        reportText: abuseFlags.reportText,
        deploymentId: abuseFlags.deploymentId,
        createdAt: abuseFlags.createdAt,
        updatedAt: abuseFlags.updatedAt,
        reviewedAt: abuseFlags.reviewedAt,
        project: {
          id: projects.id,
          name: projects.name,
          slug: projects.slug,
          status: projects.status,
          suspendedAt: projects.suspendedAt,
          serverId: projects.serverId,
        },
        organization: { id: organizations.id, name: organizations.name },
      })
      .from(abuseFlags)
      .leftJoin(projects, eq(projects.id, abuseFlags.projectId))
      .leftJoin(organizations, eq(organizations.id, abuseFlags.organizationId))
      .where(where)
      .orderBy(desc(abuseFlags.score), desc(abuseFlags.createdAt))
      .limit(params.limit)
      .offset(params.offset);
    const [{ total }] = await db
      .select({ total: sql<number>`count(*)::int` })
      .from(abuseFlags)
      .where(where);
    return { items: rows, total };
  },

  async dismissFlag(flagId: string, adminUserId: string, note: string | null) {
    const [flag] = await db.select().from(abuseFlags).where(eq(abuseFlags.id, flagId)).limit(1);
    if (!flag) throw new HTTPException(404, { message: 'Flag not found' });
    await db
      .update(abuseFlags)
      .set({ status: 'dismissed', reviewedAt: new Date(), reviewedBy: adminUserId, updatedAt: new Date() })
      .where(eq(abuseFlags.id, flagId));
    await db.insert(abuseActions).values({ projectId: flag.projectId, flagId, adminUserId, action: 'dismiss', reason: note });
  },

  /**
   * Suspend a project: stop its containers (the regular pause), mark it suspended so its owner
   * can neither resume nor deploy it, email the owner and write the audit trail. `adminUserId`
   * null means the automatic path (ABUSE_AUTO_SUSPEND).
   */
  async suspendProject(input: {
    projectId: string;
    adminUserId: string | null;
    reason: string;
    clause: AupClause;
    endsAt: Date | null;
    flagId?: string | null;
  }) {
    const [project] = await db.select().from(projects).where(eq(projects.id, input.projectId)).limit(1);
    if (!project || project.status === 'deleted') throw new HTTPException(404, { message: 'Project not found' });
    if (project.suspendedAt) throw new HTTPException(409, { message: 'Project is already suspended' });

    const { pauseProjectContainers } = await import('../lib/project-remote-cleanup');
    let containersStopped = false;
    try {
      containersStopped = await pauseProjectContainers(project);
    } catch (err) {
      containersStopped = false;
      logger.error({ err, projectId: project.id }, 'Suspension: stopping containers failed');
    }

    const now = new Date();
    await db
      .update(projects)
      .set({
        status: 'paused',
        suspendedAt: now,
        suspensionReason: input.reason,
        suspensionClause: input.clause,
        suspensionEndsAt: input.endsAt,
        sleepState: 'awake',
        updatedAt: now,
      })
      .where(eq(projects.id, project.id));

    await db.insert(abuseActions).values({
      projectId: project.id,
      flagId: input.flagId ?? null,
      adminUserId: input.adminUserId,
      action: 'suspend',
      reason: input.reason,
      clause: input.clause,
      endsAt: input.endsAt,
    });
    await db
      .update(abuseFlags)
      .set({ status: 'actioned', reviewedAt: now, reviewedBy: input.adminUserId, updatedAt: now })
      .where(and(eq(abuseFlags.projectId, project.id), eq(abuseFlags.status, 'open')));

    await activityService.log({
      organizationId: project.organizationId,
      userId: input.adminUserId ?? undefined,
      projectId: project.id,
      action: 'project.suspended',
      description: `Project "${project.name}" was suspended under the Acceptable Use Policy`,
      metadata: { clause: input.clause, endsAt: input.endsAt?.toISOString() ?? null, automatic: input.adminUserId === null },
    });

    const to = await ownerContact(project.organizationId);
    if (to) {
      await sendProjectSuspendedEmail(to, {
        projectName: project.name,
        reason: input.reason,
        clause: AUP_CLAUSES[input.clause],
        endsAt: input.endsAt,
        appealEmail: env.ABUSE_CONTACT_EMAIL,
      });
    }
    logger.warn({ projectId: project.id, clause: input.clause, automatic: input.adminUserId === null }, 'Project suspended (Acceptable Use)');
    return { containersStopped, ownerNotified: !!to };
  },

  /** Lift a suspension and start the project again. */
  async unsuspendProject(input: { projectId: string; adminUserId: string; note: string | null }) {
    const [project] = await db.select().from(projects).where(eq(projects.id, input.projectId)).limit(1);
    if (!project || project.status === 'deleted') throw new HTTPException(404, { message: 'Project not found' });
    if (!project.suspendedAt) throw new HTTPException(409, { message: 'Project is not suspended' });

    const now = new Date();
    await db
      .update(projects)
      .set({
        status: 'active',
        suspendedAt: null,
        suspensionReason: null,
        suspensionClause: null,
        suspensionEndsAt: null,
        updatedAt: now,
      })
      .where(eq(projects.id, project.id));

    const { resumeProjectContainers } = await import('../lib/project-remote-cleanup');
    let containersStarted = true;
    try {
      containersStarted = await resumeProjectContainers({ ...project, status: 'active', suspendedAt: null });
    } catch (err) {
      containersStarted = false;
      logger.error({ err, projectId: project.id }, 'Unsuspension: starting containers failed');
    }

    await db.insert(abuseActions).values({ projectId: project.id, adminUserId: input.adminUserId, action: 'unsuspend', reason: input.note });
    await activityService.log({
      organizationId: project.organizationId,
      userId: input.adminUserId,
      projectId: project.id,
      action: 'project.unsuspended',
      description: `The suspension of project "${project.name}" was lifted`,
    });

    const to = await ownerContact(project.organizationId);
    if (to) await sendProjectReinstatedEmail(to, { projectName: project.name, note: input.note });
    return { containersStarted, ownerNotified: !!to };
  },

  async clauses() {
    return AUP_CLAUSES;
  },

  async listActions(projectIds: string[]) {
    if (projectIds.length === 0) return [];
    return db
      .select()
      .from(abuseActions)
      .where(inArray(abuseActions.projectId, projectIds))
      .orderBy(desc(abuseActions.createdAt));
  },
};
