import { readFileSync } from 'node:fs';
import { X509Certificate } from 'node:crypto';
import { and, eq, inArray, ne } from 'drizzle-orm';
import { db } from '../db';
import { domains, projects } from '../db/schema/projects';
import { organizationRepository } from '../repositories/organization.repository';
import { env } from '../config/env';
import { logger } from '../lib/logger';
import { daysLeft, dueExpiryWarning, servedCertificateExpiry, FIRST_WARNING_DAYS } from '../lib/cert-expiry';
import { resolveBillingNotifyEmail } from '../lib/billing-notify';
import { sendCertificateExpiryEmail } from '../lib/email';
import { adminNotify } from './admin-notify.service';

/** Daily: what every custom domain serves, and warnings before it expires (lib/cert-expiry.ts). */
export const certExpiryService = {
  /**
   * Custom domains with an issued certificate on live projects (auto subdomains share the
   * wildcard, checked below). `domainIds` / `now` narrow and pin a run (tests).
   */
  async checkDomains(options: { domainIds?: string[]; now?: Date } = {}): Promise<{ checked: number; warned: number }> {
    const now = options.now ?? new Date();
    const rows = await db
      .select({
        id: domains.id,
        domain: domains.domain,
        notifiedAt: domains.sslExpiryNotifiedAt,
        projectId: projects.id,
        projectName: projects.name,
        organizationId: projects.organizationId,
      })
      .from(domains)
      .innerJoin(projects, eq(domains.projectId, projects.id))
      .where(
        and(
          eq(domains.isAutoGenerated, false),
          eq(domains.sslStatus, 'active'),
          ne(projects.status, 'deleted'),
          options.domainIds ? inArray(domains.id, options.domainIds) : undefined
        )
      );

    let checked = 0;
    let warned = 0;
    for (const row of rows) {
      const expiresAt = await servedCertificateExpiry(row.domain);
      if (!expiresAt) continue; // not answering — a DNS / uptime question, not an expiry one
      checked++;
      await db.update(domains).set({ sslExpiresAt: expiresAt }).where(eq(domains.id, row.id));

      const warning = dueExpiryWarning(expiresAt, row.notifiedAt, now);
      if (!warning) continue;
      const left = daysLeft(expiresAt, now);
      try {
        const [to, org] = await Promise.all([
          resolveBillingNotifyEmail(row.organizationId),
          organizationRepository.findById(row.organizationId),
        ]);
        if (to) {
          await sendCertificateExpiryEmail(to, {
            orgName: org?.name ?? '',
            domain: row.domain,
            projectName: row.projectName,
            projectId: row.projectId,
            expiresAt,
            daysLeft: left,
            final: warning === 'final',
          });
        }
        adminNotify('certificate.expiring', {
          domain: row.domain,
          project: row.projectName,
          daysLeft: left,
          expiresAt: expiresAt.toISOString(),
          warning,
        });
      } catch (err) {
        logger.error({ err, domain: row.domain }, 'Certificate expiry warning failed');
      }
      await db.update(domains).set({ sslExpiryNotifiedAt: now }).where(eq(domains.id, row.id));
      warned++;
    }
    return { checked, warned };
  },

  /**
   * The wildcard certificate of auto subdomains, where this process can read it (the control
   * plane). Operators only; repeats daily while it is due, which is the point.
   */
  checkPlatformWildcard(now: Date = new Date()): void {
    if (!env.WILDCARD_SSL_PATH || !env.PREVIEW_BASE_URL) return;
    let expiresAt: Date;
    try {
      expiresAt = new Date(new X509Certificate(readFileSync(`${env.WILDCARD_SSL_PATH}/fullchain.pem`)).validTo);
    } catch {
      return; // not on this host, or not readable
    }
    const left = daysLeft(expiresAt, now);
    if (left <= FIRST_WARNING_DAYS) {
      adminNotify('certificate.expiring', {
        domain: `*.${env.PREVIEW_BASE_URL}`,
        where: `${env.WILDCARD_SSL_PATH} on the control plane`,
        daysLeft: left,
        expiresAt: expiresAt.toISOString(),
      });
    }
  },
};
