import { HTTPException } from 'hono/http-exception';
import { eq, and, gte, ne, sql, count } from 'drizzle-orm';
import { db } from '../db';
import { projects, domains } from '../db/schema/projects';
import { deployments } from '../db/schema/deployments';
import { organizationMembers, organizationInvitations } from '../db/schema/organizations';
import { servers } from '../db/schema/servers';
import { databases } from '../db/schema/databases';
import { organizationRepository } from '../repositories/organization.repository';
import { projectRepository } from '../repositories/project.repository';
import { getEffectivePlanLimits } from '../lib/effective-plan-limits';
import { isUnlimited, type PlanType, type PlanLimits } from '../lib/plans';
import { t, type SupportedLocale } from '../i18n';
import { usageMeteringService } from './usage-metering.service';

export type CountablePlanLimit = keyof Pick<
  PlanLimits,
  'servers' | 'databases' | 'projects' | 'deploymentsPerMonth' | 'teamMembers' | 'customDomains'
>;

function startOfUtcMonth(): Date {
  const now = new Date();
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
}

export const planLimitsService = {
  async getPlan(organizationId: string): Promise<PlanType> {
    const org = await organizationRepository.findById(organizationId);
    return (org?.plan || 'free') as PlanType;
  },

  async getEffectiveLimits(organizationId: string): Promise<PlanLimits> {
    const org = await organizationRepository.findById(organizationId);
    if (!org) {
      return getEffectivePlanLimits({ plan: 'free' });
    }
    return getEffectivePlanLimits({
      plan: (org.plan || 'free') as PlanType,
      grandfatheredUntil: org.grandfatheredUntil,
      planLimitsOverride: org.planLimitsOverride as Partial<Record<string, number | boolean>> | null,
    });
  },

  async countProjects(organizationId: string): Promise<number> {
    const list = await projectRepository.findByOrganization(organizationId);
    return list.length;
  },

  async countDeploymentsThisMonth(organizationId: string): Promise<number> {
    const monthStart = startOfUtcMonth();
    const [row] = await db
      .select({ total: count() })
      .from(deployments)
      .innerJoin(projects, eq(deployments.projectId, projects.id))
      .where(
        and(
          eq(projects.organizationId, organizationId),
          gte(deployments.createdAt, monthStart),
          ne(deployments.status, 'cancelled'),
        ),
      );
    return Number(row?.total ?? 0);
  },

  async countBuildMinutesThisMonth(organizationId: string): Promise<number> {
    const monthStart = startOfUtcMonth();
    const [row] = await db
      .select({
        minutes: sql<number>`COALESCE(SUM(
          EXTRACT(EPOCH FROM (${deployments.buildFinishedAt} - ${deployments.buildStartedAt})) / 60.0
        ), 0)`,
      })
      .from(deployments)
      .innerJoin(projects, eq(deployments.projectId, projects.id))
      .where(
        and(
          eq(projects.organizationId, organizationId),
          gte(deployments.createdAt, monthStart),
          sql`${deployments.buildStartedAt} IS NOT NULL`,
          sql`${deployments.buildFinishedAt} IS NOT NULL`,
        ),
      );
    return Math.ceil(Number(row?.minutes ?? 0));
  },

  async countServers(organizationId: string): Promise<number> {
    const [row] = await db
      .select({ total: count() })
      .from(servers)
      .where(eq(servers.organizationId, organizationId));
    return Number(row?.total ?? 0);
  },

  async countDatabases(organizationId: string): Promise<number> {
    const [row] = await db
      .select({ total: count() })
      .from(databases)
      .where(eq(databases.organizationId, organizationId));
    return Number(row?.total ?? 0);
  },

  async countTeamMembers(organizationId: string): Promise<number> {
    const [memberRow] = await db
      .select({ total: count() })
      .from(organizationMembers)
      .where(eq(organizationMembers.organizationId, organizationId));
    const [inviteRow] = await db
      .select({ total: count() })
      .from(organizationInvitations)
      .where(
        and(
          eq(organizationInvitations.organizationId, organizationId),
          eq(organizationInvitations.status, 'pending'),
        ),
      );
    return Number(memberRow?.total ?? 0) + Number(inviteRow?.total ?? 0);
  },

  async countCustomDomains(organizationId: string): Promise<number> {
    const [row] = await db
      .select({ total: count() })
      .from(domains)
      .innerJoin(projects, eq(domains.projectId, projects.id))
      .where(
        and(eq(projects.organizationId, organizationId), eq(domains.isAutoGenerated, false)),
      );
    return Number(row?.total ?? 0);
  },

  async assertWithinLimit(
    organizationId: string,
    limitKey: CountablePlanLimit,
    locale: SupportedLocale,
    getCurrentCount: () => Promise<number>,
  ): Promise<void> {
    const limits = await this.getEffectiveLimits(organizationId);
    const limit = limits[limitKey];
    if (isUnlimited(limit)) return;

    const current = await getCurrentCount();
    if (current >= limit) {
      throw new HTTPException(403, {
        message: t(locale, 'planLimits', limitKey),
      });
    }
  },

  async assertServersQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    await this.assertWithinLimit(organizationId, 'servers', locale, () =>
      this.countServers(organizationId),
    );
  },

  async assertDatabasesQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    await this.assertWithinLimit(organizationId, 'databases', locale, () =>
      this.countDatabases(organizationId),
    );
  },

  async assertProjectsQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    await this.assertWithinLimit(organizationId, 'projects', locale, () =>
      this.countProjects(organizationId),
    );
  },

  async assertDeploymentsQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    await this.assertWithinLimit(organizationId, 'deploymentsPerMonth', locale, () =>
      this.countDeploymentsThisMonth(organizationId),
    );
  },

  async assertBuildMinutesQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    const limits = await this.getEffectiveLimits(organizationId);
    const limit = limits.buildMinutesPerMonth;
    if (isUnlimited(limit)) return;

    const used = await this.countBuildMinutesThisMonth(organizationId);
    if (used >= limit) {
      throw new HTTPException(403, {
        message: t(locale, 'planLimits', 'buildMinutesPerMonth'),
      });
    }
  },

  async assertStorageQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    const limits = await this.getEffectiveLimits(organizationId);
    const limit = limits.storageGb;
    if (isUnlimited(limit)) return;

    const { storageGb } = await usageMeteringService.getMonthlyUsageGb(organizationId);
    if (storageGb >= limit) {
      throw new HTTPException(403, {
        message: t(locale, 'planLimits', 'storageGb'),
      });
    }
  },

  async assertBandwidthQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    const limits = await this.getEffectiveLimits(organizationId);
    const limit = limits.bandwidthGb;
    if (isUnlimited(limit)) return;

    const { bandwidthGb } = await usageMeteringService.getMonthlyUsageGb(organizationId);
    if (bandwidthGb >= limit) {
      throw new HTTPException(403, {
        message: t(locale, 'planLimits', 'bandwidthGb'),
      });
    }
  },

  async assertTeamMembersQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    await this.assertWithinLimit(organizationId, 'teamMembers', locale, () =>
      this.countTeamMembers(organizationId),
    );
  },

  async assertCustomDomainsQuota(organizationId: string, locale: SupportedLocale): Promise<void> {
    await this.assertWithinLimit(organizationId, 'customDomains', locale, () =>
      this.countCustomDomains(organizationId),
    );
  },

  async assertPreviewDeploymentsAllowed(
    organizationId: string,
    locale: SupportedLocale,
  ): Promise<void> {
    const limits = await this.getEffectiveLimits(organizationId);
    if (!limits.previewDeployments) {
      throw new HTTPException(403, {
        message: t(locale, 'planLimits', 'previewDeployments'),
      });
    }
  },

  async assertHealthChecksAllowed(organizationId: string, locale: SupportedLocale): Promise<void> {
    const limits = await this.getEffectiveLimits(organizationId);
    if (!limits.healthChecks) {
      throw new HTTPException(403, {
        message: t(locale, 'planLimits', 'healthChecks'),
      });
    }
  },
};
