import { and, eq, gte, inArray, isNotNull, isNull, sql } from 'drizzle-orm';
import { db } from '../db';
import { projects, domains } from '../db/schema/projects';
import { servers } from '../db/schema/servers';
import { projectTrafficHourly } from '../db/schema/traffic';
import { env } from '../config/env';
import { logger } from '../lib/logger';
import { decrypt } from '../lib/encryption';
import { getSSHConnection } from '../utils/ssh';
import { resolveProjectServerId } from '../lib/runner-routing';
import { loadAbuseRules } from '../lib/abuse/rules';
import { scoreReasons } from '../lib/abuse/scan';
import {
  ConnectionTracker,
  connectionCountCommand,
  evaluateRuntime,
  parseConnectionCounts,
} from '../lib/abuse/runtime';
import { abuseService, isCoveredByPolicy } from '../services/abuse.service';

/**
 * Every 5 minutes, for active projects the hosted-service rules cover: egress over 24 hours,
 * whether in ≈ out (a relay), and how many TCP connections the app's containers hold open.
 * Volumes and counts only. Findings go to the review queue; nothing is stopped here.
 */

const SWEEP_INTERVAL_MS = 5 * 60 * 1000;
const tracker = new ConnectionTracker();

interface Candidate {
  id: string;
  slug: string;
  organizationId: string;
  serverId: string | null;
}

async function coveredCandidates(): Promise<Candidate[]> {
  const rows = await db
    .select({ id: projects.id, slug: projects.slug, organizationId: projects.organizationId, serverId: projects.serverId })
    .from(projects)
    .where(and(eq(projects.status, 'active'), isNull(projects.suspendedAt)));
  if (rows.length === 0) return [];

  const serverIds = [...new Set(rows.map((r) => r.serverId).filter((x): x is string => !!x))];
  const serverRows = serverIds.length
    ? await db.select({ id: servers.id, isManaged: servers.isManaged, provider: servers.provider }).from(servers).where(inArray(servers.id, serverIds))
    : [];
  const serverById = new Map(serverRows.map((s) => [s.id, s]));
  const domainRows = await db
    .select({ projectId: domains.projectId, domain: domains.domain, isAutoGenerated: domains.isAutoGenerated })
    .from(domains)
    .where(inArray(domains.projectId, rows.map((r) => r.id)));
  const domainsByProject = new Map<string, { domain: string; isAutoGenerated: boolean }[]>();
  for (const d of domainRows) {
    const list = domainsByProject.get(d.projectId) ?? [];
    list.push(d);
    domainsByProject.set(d.projectId, list);
  }

  return rows.filter((r) =>
    isCoveredByPolicy({
      serverId: r.serverId,
      server: r.serverId ? serverById.get(r.serverId) ?? null : null,
      domains: domainsByProject.get(r.id) ?? [],
    }),
  );
}

/** Bytes in/out per project over 24h: container counters (summing positive deltas) and nginx bytes sent. */
export async function trafficByProject(projectIds: string[]): Promise<Map<string, { egress: number; ingress: number }>> {
  const out = new Map<string, { egress: number; ingress: number }>();
  if (projectIds.length === 0) return out;
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const counters = await db.execute<{ project_id: string; tx: string | null; rx: string | null }>(sql`
    SELECT project_id, SUM(GREATEST(dtx, 0)) AS tx, SUM(GREATEST(drx, 0)) AS rx FROM (
      SELECT project_id,
        network_tx_bytes - LAG(network_tx_bytes) OVER w AS dtx,
        network_rx_bytes - LAG(network_rx_bytes) OVER w AS drx
      FROM container_metrics
      WHERE recorded_at >= ${since} AND project_id IN (${sql.join(projectIds.map((id) => sql`${id}::uuid`), sql`, `)})
      WINDOW w AS (PARTITION BY project_id, container_name ORDER BY recorded_at)
    ) d GROUP BY project_id`);
  for (const row of counters.rows) {
    out.set(row.project_id, { egress: Number(row.tx ?? 0), ingress: Number(row.rx ?? 0) });
  }

  const nginx = await db
    .select({ projectId: projectTrafficHourly.projectId, sent: sql<string>`SUM(${projectTrafficHourly.bytesSent})` })
    .from(projectTrafficHourly)
    .where(and(inArray(projectTrafficHourly.projectId, projectIds), gte(projectTrafficHourly.hour, since)))
    .groupBy(projectTrafficHourly.projectId);
  for (const row of nginx) {
    const cur = out.get(row.projectId) ?? { egress: 0, ingress: 0 };
    cur.egress = Math.max(cur.egress, Number(row.sent ?? 0));
    out.set(row.projectId, cur);
  }
  return out;
}

/** Established connections per project, one SSH session per server. Missing servers just give no count. */
async function connectionsByProject(candidates: Candidate[]): Promise<Map<string, number>> {
  const byServer = new Map<string, Candidate[]>();
  for (const c of candidates) {
    const sid = resolveProjectServerId(c);
    if (!sid) continue;
    const list = byServer.get(sid) ?? [];
    list.push(c);
    byServer.set(sid, list);
  }

  const counts = new Map<string, number>();
  for (const [serverId, list] of byServer) {
    const [server] = await db.select().from(servers).where(eq(servers.id, serverId)).limit(1);
    if (!server?.ipv4 || !server.sshPrivateKey || server.status !== 'running') continue;
    let ssh: Awaited<ReturnType<typeof getSSHConnection>> | null = null;
    try {
      ssh = await getSSHConnection({ host: server.ipv4, port: 22, username: 'root', privateKey: decrypt(server.sshPrivateKey) });
      const res = await ssh.exec(connectionCountCommand(list.map((c) => c.slug)));
      const perContainer = parseConnectionCounts(res.stdout);
      for (const c of list) {
        let total = 0;
        let seen = false;
        const re = new RegExp(`^pushify-${c.slug}(-(blue|green)(-[0-9]+)?)?$`);
        for (const [name, n] of perContainer) {
          if (re.test(name)) {
            total += n;
            seen = true;
          }
        }
        if (seen) counts.set(c.id, total);
      }
    } catch (err) {
      logger.warn({ err, serverId }, 'Abuse runtime: connection count failed');
    } finally {
      ssh?.disconnect();
    }
  }
  return counts;
}

export async function sweepRuntimeSignals(): Promise<{ checked: number; flagged: number }> {
  if (!env.ABUSE_DETECTION_ENABLED) return { checked: 0, flagged: 0 };
  const rules = loadAbuseRules();
  const candidates = await coveredCandidates();
  if (candidates.length === 0) return { checked: 0, flagged: 0 };

  const traffic = await trafficByProject(candidates.map((c) => c.id));
  const connections = await connectionsByProject(candidates);

  let flagged = 0;
  for (const c of candidates) {
    const t = traffic.get(c.id) ?? { egress: 0, ingress: 0 };
    const count = connections.get(c.id) ?? null;
    const sustained =
      count !== null &&
      tracker.record(c.id, count, rules.runtime.connections, rules.runtime.connectionsSustainedMinutes * 60_000);
    const reasons = evaluateRuntime({ egressBytes: t.egress, ingressBytes: t.ingress, connectionsSustained: sustained, connectionCount: count }, rules);
    if (reasons.length === 0) continue;
    const result = scoreReasons(reasons, rules);
    const recorded = await abuseService.recordFinding({ projectId: c.id, organizationId: c.organizationId, source: 'runtime', result });
    if (recorded) flagged++;
  }
  return { checked: candidates.length, flagged };
}

/**
 * A suspension must stay a suspension: stop the containers of every suspended project again.
 * Covers a pause that could not reach the server at the time, a container someone started by
 * hand, and projects suspended before the shared-runner fix. Stopping a stopped container is a
 * no-op, so this is safe to repeat.
 */
export async function enforceSuspensions(): Promise<{ checked: number; notStopped: number }> {
  const suspended = await db.select().from(projects).where(isNotNull(projects.suspendedAt));
  if (suspended.length === 0) return { checked: 0, notStopped: 0 };
  const { pauseProjectContainers } = await import('../lib/project-remote-cleanup');
  let notStopped = 0;
  for (const project of suspended) {
    try {
      if (!(await pauseProjectContainers(project))) notStopped++;
    } catch (err) {
      notStopped++;
      logger.warn({ err, projectId: project.id }, 'Suspension enforcement: could not stop containers');
    }
  }
  if (notStopped > 0) logger.warn({ checked: suspended.length, notStopped }, 'Suspended projects still running');
  return { checked: suspended.length, notStopped };
}

let interval: ReturnType<typeof setInterval> | null = null;
let running = false;

export function startAbuseRuntimeWorker(): void {
  if (interval) return;
  interval = setInterval(() => {
    if (running) return;
    running = true;
    // Suspensions are enforced whether or not detection is on: an admin may suspend by hand.
    enforceSuspensions()
      .catch((err) => logger.error({ err }, 'Suspension enforcement failed'))
      .then(() => (env.ABUSE_DETECTION_ENABLED ? sweepRuntimeSignals() : { checked: 0, flagged: 0 }))
      .then((r) => {
        if (r.flagged > 0) logger.warn(r, 'Abuse runtime sweep flagged projects');
      })
      .catch((err) => logger.error({ err }, 'Abuse runtime sweep failed'))
      .finally(() => {
        running = false;
      });
  }, SWEEP_INTERVAL_MS);
  logger.info(
    env.ABUSE_DETECTION_ENABLED
      ? '🛡️ Acceptable Use runtime worker started'
      : '🛡️ Suspension enforcement started (Acceptable Use detection off)',
  );
}

export function stopAbuseRuntimeWorker(): void {
  if (interval) {
    clearInterval(interval);
    interval = null;
  }
}
