import { and, eq, gte, inArray, sql } from 'drizzle-orm';
import { db } from '../db';
import {
  databases,
  deployments,
  domains,
  onboardingEmails,
  organizationMembers,
  organizations,
  projects,
  users,
} from '../db/schema';
import { buildUnsubscribeUrl } from '../lib/onboarding';
import { sendOnboardingEmail, type OnboardingEmailKey } from '../lib/email';
import { logger } from '../lib/logger';

const SWEEP_INTERVAL_MS = 60 * 60 * 1000; // hourly
const HOUR = 60 * 60 * 1000;
/** Never email organizations older than this — protects existing users at rollout. */
const MAX_ORG_AGE_MS = 30 * 24 * HOUR;

let isRunning = false;
let intervalHandle: ReturnType<typeof setInterval> | null = null;
let sweepInProgress = false;

export interface OrgProgress {
  orgId: string;
  ageMs: number;
  ownerEmail: string | null;
  ownerUserId: string | null;
  optOut: boolean;
  deployments: number;
  customDomains: number;
  databases: number;
  sent: Set<string>;
}

/**
 * State-driven, not a dumb timer: each email only goes to organizations that
 * actually need it (e.g. "connect a domain" never reaches someone who hasn't
 * deployed, "stuck?" never reaches someone who has).
 */
export function pickEmail(p: OrgProgress): OnboardingEmailKey | null {
  if (p.ageMs >= 20 * HOUR && p.deployments === 0 && !p.sent.has('first_deploy')) {
    return 'first_deploy';
  }
  if (
    p.ageMs >= 68 * HOUR &&
    p.deployments === 0 &&
    p.sent.has('first_deploy') &&
    !p.sent.has('stuck')
  ) {
    return 'stuck';
  }
  if (p.ageMs >= 68 * HOUR && p.deployments > 0 && p.customDomains === 0 && !p.sent.has('connect_domain')) {
    return 'connect_domain';
  }
  if (p.ageMs >= 7 * 24 * HOUR && p.deployments > 0 && p.databases === 0 && !p.sent.has('add_database')) {
    return 'add_database';
  }
  return null;
}

export async function sweepOnboarding(now: Date = new Date()): Promise<{ sent: number }> {
  const stats = { sent: 0 };
  const cutoff = new Date(now.getTime() - MAX_ORG_AGE_MS);

  const orgs = await db
    .select({ id: organizations.id, createdAt: organizations.createdAt })
    .from(organizations)
    .where(gte(organizations.createdAt, cutoff));
  if (orgs.length === 0) return stats;
  const orgIds = orgs.map((o) => o.id);

  const [owners, deployCounts, domainCounts, dbCounts, sentRows] = await Promise.all([
    db
      .select({
        orgId: organizationMembers.organizationId,
        email: users.email,
        userId: users.id,
        optOut: users.onboardingEmailsOptOut,
      })
      .from(organizationMembers)
      .innerJoin(users, eq(users.id, organizationMembers.userId))
      .where(
        and(inArray(organizationMembers.organizationId, orgIds), eq(organizationMembers.role, 'owner'))
      ),
    db
      .select({ orgId: projects.organizationId, count: sql<number>`count(*)::int` })
      .from(deployments)
      .innerJoin(projects, eq(projects.id, deployments.projectId))
      .where(inArray(projects.organizationId, orgIds))
      .groupBy(projects.organizationId),
    db
      .select({ orgId: projects.organizationId, count: sql<number>`count(*)::int` })
      .from(domains)
      .innerJoin(projects, eq(projects.id, domains.projectId))
      .where(and(inArray(projects.organizationId, orgIds), eq(domains.isAutoGenerated, false)))
      .groupBy(projects.organizationId),
    db
      .select({ orgId: databases.organizationId, count: sql<number>`count(*)::int` })
      .from(databases)
      .where(inArray(databases.organizationId, orgIds))
      .groupBy(databases.organizationId),
    db
      .select({ orgId: onboardingEmails.organizationId, emailKey: onboardingEmails.emailKey })
      .from(onboardingEmails)
      .where(inArray(onboardingEmails.organizationId, orgIds)),
  ]);

  const ownerByOrg = new Map(owners.map((o) => [o.orgId, o]));
  const countMap = (rows: { orgId: string; count: number }[]) =>
    new Map(rows.map((r) => [r.orgId, r.count]));
  const deploysByOrg = countMap(deployCounts);
  const domainsByOrg = countMap(domainCounts);
  const dbsByOrg = countMap(dbCounts);
  const sentByOrg = new Map<string, Set<string>>();
  for (const row of sentRows) {
    if (!sentByOrg.has(row.orgId)) sentByOrg.set(row.orgId, new Set());
    sentByOrg.get(row.orgId)!.add(row.emailKey);
  }

  for (const org of orgs) {
    try {
      const owner = ownerByOrg.get(org.id);
      if (!owner?.email || owner.optOut) continue;

      const progress: OrgProgress = {
        orgId: org.id,
        ageMs: now.getTime() - org.createdAt.getTime(),
        ownerEmail: owner.email,
        ownerUserId: owner.userId,
        optOut: owner.optOut,
        deployments: deploysByOrg.get(org.id) ?? 0,
        customDomains: domainsByOrg.get(org.id) ?? 0,
        databases: dbsByOrg.get(org.id) ?? 0,
        sent: sentByOrg.get(org.id) ?? new Set(),
      };

      const key = pickEmail(progress);
      if (!key) continue;

      // Claim BEFORE sending — the unique index makes concurrent sweeps safe,
      // and a failed send is deleted so the next sweep retries.
      const [claimed] = await db
        .insert(onboardingEmails)
        .values({ organizationId: org.id, emailKey: key })
        .onConflictDoNothing()
        .returning({ id: onboardingEmails.id });
      if (!claimed) continue;

      const unsubscribeUrl = await buildUnsubscribeUrl(owner.userId);
      const ok = await sendOnboardingEmail(owner.email, key, unsubscribeUrl);
      if (!ok) {
        await db.delete(onboardingEmails).where(eq(onboardingEmails.id, claimed.id));
        continue;
      }
      stats.sent++;
    } catch (error) {
      logger.error({ err: error, orgId: org.id }, 'Onboarding sweep item failed');
    }
  }

  return stats;
}

export function startOnboardingWorker(): void {
  if (isRunning) return;
  isRunning = true;
  logger.info('Onboarding email worker started (hourly, state-driven)');

  const tick = () => {
    if (sweepInProgress) return;
    sweepInProgress = true;
    sweepOnboarding()
      .then((stats) => {
        if (stats.sent > 0) logger.info(stats, 'Onboarding sweep sent emails');
      })
      .catch((err) => logger.error({ err }, 'Onboarding sweep failed'))
      .finally(() => {
        sweepInProgress = false;
      });
  };

  tick();
  intervalHandle = setInterval(tick, SWEEP_INTERVAL_MS);
}

export function stopOnboardingWorker(): void {
  isRunning = false;
  if (intervalHandle) {
    clearInterval(intervalHandle);
    intervalHandle = null;
  }
  logger.info('Onboarding email worker stopped');
}
